Repository tidbcloud/dbaas-docs, pull requests merged in 2020-09, with the labels that each got.

#11 Update description and format, fix typos
  TOC.md
  connect-to-tidb-cluster.md
  export-data-from-tidb-cloud.md
  limitations-and-quotas.md
  migrate-data-into-tidb.md
  release-notes.md
  supported-tidb-versions.md
  terms-of-service.md
  tidb-cloud-billing.md
  use-htap-cluster.md
Labels: type/bug-fix, type/enhancement

#10 Optimize organization and wording about vpc peering
  TOC.md
  glossary.md
  media/vpc-peering/aws-vpc-guide-2.jpg
  media/vpc-peering/aws-vpc-guide-6.png
  media/vpc-peering/aws-vpc-guide-7.png
  media/vpc-peering/aws-vpc-guide-8.png
  media/vpc-peering/aws-vpc-guide-9.png
  media/vpc-peering/tidb-cloud-cluster-info-connect-button.png
  media/vpc-peering/tidb-cloud-cluster-info-connection-info-dashboard.png
  media/vpc-peering/tidb-cloud-vpc-peering-create-dashboard.png
  media/vpc-peering/tidb-cloud-vpc-peering-env-check-information.png
  media/vpc-peering/vpc-peering-topology.png
  set-up-vpc-peering-connections.md
Labels: size/medium, type/enhancement

#12 Fix an anchor link by removing one word
  set-up-vpc-peering-connections.md
Labels: size/small, type/bug-fix

#19 Hotfix release-20200914
  release-notes.md
Labels: size/small, status/DNM

#20 Update connect-to-tidb-cluster.md
  connect-to-tidb-cluster.md
Labels: status/require-change

#21 Fix a list display error
  connect-to-tidb-cluster.md
Labels: size/small

#17 Add markdownlint, link, anchor checks
  .circleci/config.yml
  scripts/check-tags.py
  scripts/generate_pdf.sh
  scripts/markdown-link-check.tpl
  scripts/markdownlint
  scripts/merge_by_toc.py
  scripts/upload.py
  scripts/verify-link-anchors.sh
  scripts/verify-links.sh
  templates/copyright.tex
  templates/template.tex
Labels: type/enhancement

#23 Move from circleci to github workflows
  .circleci/config.yml
  .github/workflows/ci.yaml
  .github/workflows/link-check.yaml
  .markdownlint.yaml
  _index.md
  hack/check-tags.py
  hack/markdown-link-check.tpl
  hack/verify-link-anchors.sh
  hack/verify-links.sh
  release-notes.md
  scripts/verify-links.sh
Labels: type/enhancement

#25 Fix MySQL 8.0 client command error
  connect-to-tidb-cluster.md
Labels: type/bug-fix
